### ISSUE TITLE
Some DOI actions do not trigger log in control

### ISSUE THREAD

**Issue by hofmannc** [MPDL/DOI#12]
Testserver: https://test.doi.mpdl.mpg.de/doxi/
Browser: ff 
Version: test date 15.02.2017          
User: not yet logged in

Actions: try actions without being logged in
Start page -> DOI -> “Delete” ->  enter invalid/non existing DOI -> “Try it out” -> Response Body “No content/DOI doesn’t exist”

Observation: Some DOI actions do not require a log in 

delete 
get /doi/{doi}
post /doi/{doi}
put /doi/{doi}

Expected Result: User gets Log in control after “try it out” of first action

**Comment by haarli** [comment]
If the DOI format is invalid, then no login is required and a 404 response code is given. This is an intended behaviour.
