### ISSUE TITLE
No log in control for PID if earlier logged in to DOI

### ISSUE THREAD

**Issue by hofmannc** [MPDL/DOI#13]
Testserver: https://test.doi.mpdl.mpg.de/doxi/
Browser: ff
Version: test date 15.02.2017
User: doiuser

Actions: get/pid/cache/size
1. Start page -> DOI -> “get/doi” -> “Try it out” -> enter valid username and password -> "ok"
2. -> PID -> "get pid/cache/size" -> 
![grafik](https://cloud.githubusercontent.com/assets/14921701/22983506/9a13a24a-f3a2-11e6-9ce8-e297e29a8b5e.png)

Observation: log in control does not pop up for PID section if earlier logged in to DOI section

Expected Result: User is provided with log in control after switching from DOI to PID section

**Comment by haarli** [comment]
Due to the HTTP Basic Authentication, it is currently not possible to logout a user when switching rom PID to DOI (or vice versa). The credentials are still stored by the browser.
