### ISSUE TITLE
put /doi: If metadata includes a dissenting DOI it might be better to throw an error

### ISSUE THREAD

**Issue by ioverka** [MPDL/DOI#4]
Your DOI DAU just confused
`put /doi`
with 
`put /doi/{doi} `
and oversaw that the DOxI interface requested a suffix instead of a doi. So, I just created DOIs like:
http://doi.org/10.17617/1.10.17617/1.1V :fearful: 

The DOI value in the metadata was correct, e.g.:
```
<?xml version='1.0' encoding='UTF-8'?>
<resource xmlns='http://datacite.org/schema/kernel-3' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://datacite.org/schema/kernel-3 http://schema.datacite.org/meta/kernel-3/metadata.xsd'>
<identifier identifierType='DOI'>10.17617/1.1V</identifier>
<creators>
	<creator>
		<creatorName>Rempe, Gerhard</creatorName>
	</creator>
	<creator>
		<creatorName>Glöckner, Rosa</creatorName>
		<affiliation>Max-Planck-Institut für Quantenoptik</affiliation>
	</creator>
</creators>
<titles>
	<title>Ultrakalte Moleküle</title>
</titles>
<publisher>Max-Planck-Gesellschaft zur Förderung der Wissenschaften e.V.</publisher>
<publicationYear>2016</publicationYear>
<resourceType resourceTypeGeneral='Text'></resourceType>
</resource>
```

... but DOxI was so clever to modify the xml to get the request passed:

```
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns="http://datacite.org/schema/kernel-3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://datacite.org/schema/kernel-3 http://schema.datacite.org/meta/kernel-3/metadata.xsd">  
  <identifier identifierType="DOI">10.17617/1.10.17617/1.1V</identifier>  
  <creators> 
    <creator> 
      <creatorName>Rempe, Gerhard</creatorName> 
    </creator>  
    <creator> 
      <creatorName>Glöckner, Rosa</creatorName>  
      <affiliation>Max-Planck-Institut für Quantenoptik</affiliation> 
    </creator> 
  </creators>  
  <titles> 
    <title>Ultrakalte Moleküle</title> 
  </titles>  
  <publisher>Max-Planck-Gesellschaft zur Förderung der Wissenschaften e.V.</publisher>  
  <publicationYear>2016</publicationYear>  
  <resourceType resourceTypeGeneral="Text"/> 
</resource>
```

Maybe it would be better to throw an error if the metadata xml provided includes a value for `<identifier identifierType="DOI">` instead of automatically replacing the DOI by the generated value? 

Or: Deactivate the method completely because nobody uses it right now? ... I fear that I'll run into this problem again...

**Comment by ioverka** [comment]
Uuups, it looks like 

`put /doi`

is used by at least one service. Any chance for implementing the error management?

**Comment by ioverka** [comment]
Results from meeting on September 20th:

After considering several options (e.g. provide DOI via request parameter or metadata only), we decided to keep the main functionalities as it is but add an exception, thus:
- the DOI value will always be replaced/overwritten by DOxI
- following metadata xml are valid inputs for DOxI: 
   1. xml without `<identifier identifierType='DOI'>` element
   1. xml with an empty `<identifier identifierType='DOI'>` element
   1. xml with an filled `<identifier identifierType='DOI'>` element
- for `PUT /doi/{doi}`, the last case will throw an error if the DOI provided in the XML isn't identical to the DOI from the PUT request

**Comment by haarli** [comment]
Option i. cannot be realized easily.
Anything else is implemented.

**Comment by ioverka** [comment]
tested successfully ;)
