### ISSUE TITLE
Misleading error message: "Problem replacing DOI in metadata"

### ISSUE THREAD

**Issue by ioverka** [MPDL/DOI#6]
The DOxI replace method is executed with each PUT /doi request and throws the error "Problem replacing DOI in metadata" if something went wrong. This is also true if the XML transformation notices invalid XML (e.g. missing closing tags). We should consider to provide more accurate error messages.

**Comment by ioverka** [comment]
Result from meeting on September 20th:
- the default error message should be modified to something like "Invalid XML provided"
- if possible more specific error messages would be appreciated

**Comment by ioverka** [comment]
harharharrr... inga assigned responsibilities...

**Comment by haarli** [comment]
Message changed to "The provided metadata xml is not well-formed."
