### ISSUE TITLE
DOI created, but not minted

### ISSUE THREAD

**Issue by ioverka** [MPDL/DOI#7]
Sometimes, an DOI is created, but not minted:
- on test: 10.15771/16
- on production: 10.17617/3.E and 10.17617/3.D

**Comment by ioverka** [comment]
Check with TIB Hannover:

- can non-minted DOIs been deleted
- how to detect non-minted DOI via its API

**Comment by haarli** [comment]
Non-minted DOIs can be manually deleted by TIB. Not possible with API
